[tool.black]
line-length = 88

[tool.pylint.MASTER]
persistent = 1

[tool.pylint.REPORT]
score = 1

[tool.pylint.MISCELLANEOUS]
notes = "FIXME, XXX, TODO"

[tool.pylint.TYPECHECK]
ignore-mixin-members = 1

[tool.pylint.FORMAT]
max-line-length = 100

# [tool.pylint.DESIGN]
# # Maximum number of arguments for function / method.
# max-args=5

# # Maximum number of attributes for a class (see R0902).
# max-attributes=7

# # Maximum number of boolean expressions in an if statement (see R0916).
# max-bool-expr=5

# # Maximum number of branch for function / method body.
# max-branches=12

# # Maximum number of locals for function / method body.
# max-locals=15

# # Maximum number of parents for a class (see R0901).
# max-parents=7

# # Maximum number of public methods for a class (see R0904).
# max-public-methods=20

# # Maximum number of return / yield for function / method body.
# max-returns=6

# # Maximum number of statements in function / method body.
# max-statements=50

# # Minimum number of public methods for a class (see R0903).
# min-public-methods=2

[tool.pylint.EXCEPTIONS]

# Exceptions that will emit a warning when being caught. Defaults to
# "BaseException, Exception".
overgeneral-exceptions = "BaseException,Exception"
