name: Deploy Package

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Build package
        run: poetry build
      - name: Upload distributions artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Tag
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?$ ]];
          then
            exit 1
          fi
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Download distributions
        uses: actions/download-artifact@v3
        with:
          name: distributions
          path: dist/
      - name: Upload package to Pypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo "Uploading to Pypi"
          poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --no-interaction --verbose
