# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[deploy]"
      - name: Build package
        run: |
          python setup.py dists
      - name: Check with twine that distributions are OK
        run: |
          twine check --strict dist/*
      - name: Upload distributions artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributions
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v2
        with:
          name: distributions
          path: dist/
      - name: Upload package to Pypi
        run: |
          echo "Uploading to Pypi"
          ls -lah
