name: Test Package

on:
  push:
    branches:
      - main
      - develop
      - chore/**
      - dev/**
      - feat/**
      - feature/**
      - fix/**
      - refacto/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install package and linter
        run: uv sync --all-extras

      - name: Run linter to detect errors
        run: uv run ruff check --output-format=concise manen/

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Test with pytest
        run: uv run pytest
