name: Test Package

on:
  push:
    branches:
      - main
      - develop
      - chore/**
      - dev/**
      - feature/**
      - fix/**
      - refacto/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install package and linter
        run: |
          python -m pip install --upgrade pip
          pip install ".[lint]"
      - name: Run linter to detect errors
        run: |
          pylint -E --rcfile=./.pylintrc ./manen/
      - name: Run isort to detect incorrectly sorted imports
        run: |
          isort --check-only manen/

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
      - name: Test with pytest
        run: |
          pytest
