name: Test Package

on:
  push:
    branches:
      - main
      - develop
      - chore/**
      - dev/**
      - feat/**
      - feature/**
      - fix/**
      - refacto/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
      - name: Install package and linter
        run: rye sync
      - name: Run linter to detect errors
        run: rye run ruff check --output-format=concise manen/

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Install rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
      - name: Install dependencies
        run: rye sync
      - name: Test with pytest
        run: rye run pytest
